### ISSUE TITLE
OK first draft of the site is done, now we should do a redesign with devel branch

### ISSUE THREAD

**Issue by bcaffo** [jhpce-jhu/jhpce_mkdocs#4]
First draft of the site is done. We should now do a redesign with devel branch 
Current live site [https://jhpce-jhu.github.io/jhpce_mkdocs/](https://jhpce-jhu.github.io/jhpce_mkdocs/)

**Comment by mamiller615** [comment]
Closing. We've gotten rid of the "devel" branch, plus issues are being tracked under the normal "jhpce" issues list.
